// Player skins (pure data, no three.js). The 3D character builder reads `colors`, `hat`, `pack`,
// `metal`, `glow` and `trail`; the shop and economy read `price`, `source` and `rarity`.
//
// price:  { coins: n } or { gems: n }, or null when the skin is not sold.
// source: 'default' (owned from the start) | 'shop' | 'daily' (7th daily reward) | 'achievement:<id>'
// hat:    none | cap | bandana | chef | pirate | headband | helmet | horns | space | antenna | wizard | crown | halo | garland
// pack:   satchel | basket | jetpack | cape | wings
// metal:  true -> metallic/shiny body material (robot, knight)
// glow:   emissive accent colour or null
// trail:  colour of the sparkle trail left while running, or null

export const RARITY = {
  common: { name: 'Common', color: '#9aa3b2' },
  rare: { name: 'Rare', color: '#3d9bff' },
  epic: { name: 'Epic', color: '#a45bff' },
  legendary: { name: 'Legendary', color: '#ffb300' },
};

export const SKINS = [
  {
    id: 'explorer',
    name: 'Explorer',
    rarity: 'common',
    price: null,
    source: 'default',
    desc: 'Ready for any island.',
    colors: { body: '#3d7bff', accent: '#ffc83d', pants: '#2e3a59', skin: '#f2c29b', hair: '#3b2a20', boots: '#6b4428' },
    hat: 'cap',
    pack: 'satchel',
    metal: false,
    glow: null,
    trail: null,
  },
  {
    id: 'scout',
    name: 'Scout',
    rarity: 'common',
    price: { coins: 400 },
    source: 'shop',
    desc: 'Knows every shortcut. Probably.',
    colors: { body: '#3fae5a', accent: '#f4e3b5', pants: '#6b5a3a', skin: '#d9a07a', hair: '#1e1a18', boots: '#4a3322' },
    hat: 'bandana',
    pack: 'basket',
    metal: false,
    glow: null,
    trail: null,
  },
  {
    id: 'chef',
    name: 'Island Chef',
    rarity: 'common',
    price: { coins: 600 },
    source: 'shop',
    desc: 'Crafts like it is a recipe. Because it is.',
    colors: { body: '#f7f7f2', accent: '#ff5a5a', pants: '#2f2f38', skin: '#f0c09a', hair: '#6b3f22', boots: '#2a2a2a' },
    hat: 'chef',
    pack: 'basket',
    metal: false,
    glow: null,
    trail: null,
  },
  {
    id: 'pirate',
    name: 'Pirate',
    rarity: 'rare',
    price: { coins: 900 },
    source: 'shop',
    desc: 'Takes resources. Calls it treasure.',
    colors: { body: '#c8323c', accent: '#f2d16b', pants: '#222030', skin: '#e2b08a', hair: '#141014', boots: '#1a1414' },
    hat: 'pirate',
    pack: 'satchel',
    metal: false,
    glow: null,
    trail: null,
  },
  {
    id: 'ninja',
    name: 'Ninja',
    rarity: 'rare',
    price: { coins: 1200 },
    source: 'shop',
    desc: 'The rival cannot read what it cannot see.',
    colors: { body: '#23232b', accent: '#e8384f', pants: '#1a1a20', skin: '#e6b48f', hair: '#0e0e12', boots: '#111114' },
    hat: 'headband',
    pack: 'cape',
    metal: false,
    glow: null,
    trail: '#e8384f',
  },
  {
    id: 'knight',
    name: 'Knight',
    rarity: 'rare',
    price: { coins: 1500 },
    source: 'shop',
    desc: 'Clanks loudly. Crafts nobly.',
    colors: { body: '#b8c2cf', accent: '#2f5fd0', pants: '#7d8794', skin: '#f0c49c', hair: '#8a5a2b', boots: '#5d6570' },
    hat: 'helmet',
    pack: 'cape',
    metal: true,
    glow: null,
    trail: null,
  },
  {
    id: 'viking',
    name: 'Viking',
    rarity: 'rare',
    price: { coins: 1500 },
    source: 'shop',
    desc: 'Sails in, gathers everything, sails out.',
    colors: { body: '#8a5a34', accent: '#d9d2c3', pants: '#4a3a2a', skin: '#f2c8a4', hair: '#d9882e', boots: '#3a2a1c' },
    hat: 'horns',
    pack: 'satchel',
    metal: false,
    glow: null,
    trail: null,
  },
  {
    id: 'festival',
    name: 'Festival Lights',
    rarity: 'epic',
    price: null,
    source: 'daily',
    desc: 'Claimed on day 7 of the daily rewards. Glows with marigold light.',
    colors: { body: '#ff9f1c', accent: '#ffd166', pants: '#b5179e', skin: '#d9a07a', hair: '#1e1414', boots: '#7a1a5a' },
    hat: 'garland',
    pack: 'satchel',
    metal: false,
    glow: '#ffb347',
    trail: '#ffd166',
  },
  {
    id: 'astronaut',
    name: 'Astronaut',
    rarity: 'epic',
    price: { gems: 60 },
    source: 'shop',
    desc: 'One small step for crafting.',
    colors: { body: '#f2f4f8', accent: '#ff7b2e', pants: '#dfe3ea', skin: '#f0c49c', hair: '#3b2a20', boots: '#9aa3b2' },
    hat: 'space',
    pack: 'jetpack',
    metal: false,
    glow: '#7fd6ff',
    trail: '#bff0ff',
  },
  {
    id: 'robot',
    name: 'Robo-Crafter',
    rarity: 'epic',
    price: { gems: 80 },
    source: 'shop',
    desc: 'Beep. Predict me. I dare you.',
    colors: { body: '#9fb3c8', accent: '#3dffb0', pants: '#6f8298', skin: '#c9d6e3', hair: '#5a6b80', boots: '#4a5868' },
    hat: 'antenna',
    pack: 'jetpack',
    metal: true,
    glow: '#3dffb0',
    trail: '#3dffb0',
  },
  {
    id: 'wizard',
    name: 'Wizard',
    rarity: 'epic',
    price: { gems: 100 },
    source: 'shop',
    desc: 'Crafts by magic. Mostly by walking.',
    colors: { body: '#5b3cc4', accent: '#ffd23d', pants: '#3a2780', skin: '#f2c8a4', hair: '#e8e8f0', boots: '#2a1d5c' },
    hat: 'wizard',
    pack: 'cape',
    metal: false,
    glow: '#b69cff',
    trail: '#d9c8ff',
  },
  {
    id: 'royal',
    name: 'Island Royal',
    rarity: 'legendary',
    price: null,
    source: 'achievement:mimic',
    desc: 'Awarded for beating MIMIC in the Adventure.',
    colors: { body: '#7a1f3d', accent: '#ffd23d', pants: '#f4efe6', skin: '#e6b48f', hair: '#2a1a12', boots: '#3a1020' },
    hat: 'crown',
    pack: 'cape',
    metal: false,
    glow: '#ffd23d',
    trail: '#ffe07a',
  },
  {
    id: 'golden',
    name: 'Golden Crafter',
    rarity: 'legendary',
    price: { gems: 200 },
    source: 'shop',
    desc: 'Pure gold, head to boots. Leaves sparkles everywhere.',
    colors: { body: '#ffc83d', accent: '#fff3b0', pants: '#e0a82e', skin: '#ffd97a', hair: '#e6a817', boots: '#c98f1a' },
    hat: 'halo',
    pack: 'wings',
    metal: true,
    glow: '#ffe07a',
    trail: '#fff3b0',
  },
];

export const SKIN_BY_ID = Object.fromEntries(SKINS.map((s) => [s.id, s]));
export const DEFAULT_SKIN = 'explorer';
